version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - web2
      - web3

  web:
    build: ./
    volumes:
      - .:/src
    environment:
      HOST: 0.0.0.0
      PORT: 3030
      MYSQL_HOST: mysql
      MYSQL_DATABASE: api_client_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: supersecure123

    depends_on:
      - mysql
    command: "npm start"

  web2:
    build: ./
    volumes:
      - .:/src
    environment:
      HOST: 0.0.0.0
      PORT: 3030
      MYSQL_HOST: mysql
      MYSQL_DATABASE: api_client_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: supersecure123

    depends_on:
      - mysql
    command: "node index.js"

  web3:
    build: ./
    volumes:
      - .:/src
    environment:
      HOST: 0.0.0.0
      PORT: 3030
      MYSQL_HOST: mysql
      MYSQL_DATABASE: api_client_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: supersecure123

    depends_on:
      - mysql

    command: "node index.js"

  mysql:
    environment:
      MYSQL_DATABASE: api_client_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: supersecure123
      MYSQL_ROOT_PASSWORD: secretsqlpass89721

    image: mysql:5.7
    volumes:
        - ./dev/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
